name: Deploy My forest to Pages

on:
  push:
    paths-ignore:
      - "LICENSE"
      - "README.md"
    branches:
      - main

# Allow 1 concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-22.04 # ubuntu-latest is currently 22.04, but being explicit is fine
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: recursive

      # <<<--- ADDED STEP: Free up disk space early --->>>
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main # Use a specific commit SHA or tag for stability if preferred
        with:
          tool-cache: true # Changed from your example 'false' to 'true' to actually remove the tool cache
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: true
      # Boost installation with caching
      - name: Cache boost libraries
        uses: actions/cache@v4
        id: cache-boost
        with:
          path: ~/boost
          key: libboost1.74-dev-${{ runner.os }}  # Update version to match your needs

      - name: Install Boost
        env:
          CACHE_HIT: ${{ steps.cache-boost.outputs.cache-hit }}
        run: |
          if [[ "$CACHE_HIT" == 'true' ]]; then
            sudo cp --force --recursive ~/boost/* /
          else
            sudo apt-get update && \
            sudo apt-get install -yq --no-install-recommends \
            libboost-all-dev \
            libev4 \
            bubblewrap \
            musl \
            musl-dev \
            musl-tools
            mkdir -p ~/boost
            for dep in libboost-all-dev; do
                dpkg -L $dep | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/boost/
            done
          fi

      # Build and test project
      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build project
        run: cmake --build build --parallel 2
        
      - uses: extractions/setup-just@v1
        with:
          just-version: 1.40.0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.29
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
            version: latest
      - name: Setup TeX Live Minimal
        uses: teatimeguest/setup-texlive-action@v3
        id: setup_texlive
        with:
          packages: > # Minimal set based on ent/tex analysis
            scheme-basic
            amsmath amsfonts amssymb graphicx geometry ifthen xcolor hyperref float booktabs
            enumerate xspace xpatch mathtools stmaryrd csquotes standalone microtype tools collection-latexrecommended
            fontspec newpxtext newpxmath utfsym newunicodechar collection-fontsrecommended
            listings
            tikz pgfplots tikz-cd tikz-3dplot tkz-euclide contour dot2texi
            algpseudocodex pseudo tabto tabularx
            amsthm thmtools mdframed tcolorbox ntheorem
            imakeidx cleveref backref makeindex bibtex
            physics worldflags todonotes
            xelatex
      - name: Cache HTML files
        uses: actions/cache@v4
        with:
          path: output/*.html
          key: ${{ runner.os }}-html-${{ hashFiles('output/*.xml', 'output/*.xsl') }}
          restore-keys: |
            ${{ runner.os }}-html-

      - name: Setup Pages
        if: ${{ !env.ACT }}
        id: pages
        uses: actions/configure-pages@v5

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.3.0" # Use a specific version compatible with forester if needed
          dune-cache: true

      - name: Cache opam packages
        uses: actions/cache@v4
        with:
           path: ~/.opam
           # Use a key that includes the OCaml version and potentially OS
           key: ${{ runner.os }}-ocaml-${{ matrix.ocaml-compiler || '5.3.0' }}-opam-${{ hashFiles('**/*.opam') }}
           restore-keys: |
            ${{ runner.os }}-ocaml-${{ matrix.ocaml-compiler || '5.3.0' }}-opam-
            ${{ runner.os }}-ocaml-
            ${{ runner.os }}-opam-

      - name: Check if forester is already installed and working
        id: check_forester # Give the step an ID to reference its outcome
        run: |
          eval $(opam env)
          export TERM=xterm-256color
          echo "Attempting to find forester..."
          opam exec -- forester --version
        # Don't fail the workflow if forester isn't found; we'll install it later.
        continue-on-error: true

      - name: Install System Dependencies (if needed)
        # Only run this step if the check_forester step failed (i.e., forester wasn't found)
        if: steps.check_forester.outcome == 'failure'
        run: |
          echo "Forester not found or check failed. Installing system dependencies..."
          sudo apt-get update && sudo apt-get install -y libev-dev

      - name: Install forester (if needed)
        # Only run this step if the check_forester step failed
        if: steps.check_forester.outcome == 'failure'
        run: |
          echo "Forester not found or check failed. Installing forester via opam..."
          opam update # Good practice before pinning/installing
          # Pin the specific commit
          opam pin add forester git+https://git.sr.ht/~jonsterling/ocaml-forester#56de06afe952d752c1a13fdcd8bb56c5fef9956f --yes
          # Install dependencies first, then the package itself
          opam install forester --yes --deps-only
          opam install forester --yes
          echo "Forester installation complete."

  

      # Add your subsequent steps that use forester here
      # - name: Use forester
      #   run: opam exec -- forester ... your command ...
      # https://github.com/astral-sh/setup-uv
      - name: Setup Python via uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.27"
          # enable-cache: true # UV cache might also consume space

      - name: Build with forester
        run: |
          eval $(opam env)
          export TERM=xterm-256color
          opam exec -- forester --version
          bash ./build.sh
      - name: Check for PDF files
        run: |
          pdf_count=$(find ./output -name "*.pdf" | wc -l)
          if [ "$pdf_count" -eq 0 ]; then
            echo "Error: No PDF files found in the output directory."
          fi
          echo "Found $pdf_count PDF files."
      - name: Fix permissions
        run: |
          chmod -c -R +rX "./output/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload Pages artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

  # Deploy job
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
